- title: Write a Learning Lab course
tagline: Write a Learning Lab course yes
description: Write a Learning Lab course
template:
  name: lab-starter
  repo: write-a-ll-course-template
before:
  - type: createIssue
    title: Welcome
    body: welcome.md
    data:
      prUrl: '%payload.repository.html_url%/compare/master...add-metadata?expand=1'
steps:

# 1
- title: Open a PR to begin crafting your course
  description: Open a PR to begin crafting your course
  event: pull_request.opened
  actions:
  - type: gate
    left: '%payload.pull_request.head.ref%'
    operator: ===
    right: add-metadata
    else:
    - type: respond
      with: e-branch.md
  - type: respond
    with: add-title.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
      title: An amazing course by %payload.sender.login%.
      ```
    position: 6

# 2
- title: Give your course a title
  description: Give your course a title
  event: pull_request.synchronize
  actions: 
  - type: getFileContents
    action_id: fileContents
    filename: 'config.yml'
  - type: gate
    left: '/^title:.+/gm'
    operator: test
    right: '%actions.fileContents%'
    else:
    - type: respond
      with: e-no-title.md
  - type: respond
    with: add-template.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        repo: lab-starter-template
      ```
    position: 13

# 3
- title: Point to the template repo
  description: Point to the template repo
  event: pull_request.synchronize
  actions:
  - type: respond
    with: add-repo-name.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        name: my-sparkles-repo
      ```
    position: 12

# 4
- title: Give the learner's repo a name
  description: Give the learner's repo a name
  event: pull_request.synchronize
  actions:
  - type: respond
    with: create-issue.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
      - type: createIssue
      ```
    position: 22
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        title: Welcome
      ```
    position: 23
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        body: welcome-text.md
      ```
    position: 24

# 5
- title: Create an issue using Learning Lab
  description: Create an issue using Learning Lab
  event: pull_request.synchronize
  actions: 
  - type: respond
    with: add-response.md

# 6
- title: Create your first response
  description: Create your first response
  event: pull_request.synchronize
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:responses/welcome-text.md
    else:
      type: respond
      with: e-no-response.md
  - type: respond
    with: add-first-step.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
      - title: Create a new PR
      ```
    position: 33
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        description: Add your name to the README.md file in your new PR
      ```
    position: 34

# 7
- title: Name your first step and give it a description
  description: Name your first step and give it a description
  event: pull_request.synchronize
  actions:
  - type: respond
    with: add-trigger.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        event: pull_request.opened
      ```
    position: 35

# 8
- title: Trigger your first step with a GitHub event
  description: Trigger your first step with a GitHub event
  event: pull_request.synchronize
  actions:
  - type: respond
    with: validate.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        - type: gate
      ```
    position: 40

# 9
- title: Validate a learner's PR
  description: Validate a learner's PR
  event: pull_request.synchronize
  actions:
  - type: respond
    with: add-context.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
          left: '%payload.pull_request.title%'
      ```
    position: 41
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
          operator: ===
      ```
    position: 42
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
          right: Add name to README
      ```
    position: 43

# 10
- title: Use contextual information to validate
  description: Use contextual information to validate
  event: pull_request.synchronize
  actions:
  - type: respond
    with: respond-success.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        - type: respond
      ```
    position: 45
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
          with: pr-opened.md
      ```
    position: 46

# 11
- title: Respond to a learner's successful PR
  description: Respond to a learner's successful PR
  event: pull_request.synchronize
  actions:
  - type: respond
    with: add-descriptions.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
      tagline: Learn how to open a PR
      ```
    position: 7
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
      description: Go from 0 to PR 1 in less than 10 minutes with this course. 
      ```
    position: 8

# 12
- title: Add some descriptions to your course
  description: Add some descriptions to your course
  event: pull_request.synchronize
  actions:
  - type: respond
    with: add-readme.md

# 13
- title: Add a README to your course
  description: Add a README to your course
  event: pull_request.synchronize
  actions:
  - type: respond
    with: publish.md

# 14
- title: Publish your course to the sandbox environment
  description: Publish your course to the sandbox environment
  event: pull_request.closed
  actions: 
  - type: respond
    with: congratulations.md
  
